import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useDispatch, useSelector } from 'react-redux'
import Sample from '../components/Sample'
import { LogState } from '../features/log'
import { AppState } from '../store'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const { count, log } = useSelector<
    AppState,
    { count: number; log: LogState }
  >((state) => ({
    count: state.counter.count,
    log: state.log,
  }));
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div style={{ padding: '12px', width: '400px', backgroundColor: '#ccc' }}>
        <h1>App{count}</h1>
        <Sample samplePropData="Data passed from parent." />
      </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
